version: '3'

services:
  redis:
      image: redis:latest # Docker-образ для Redis
      container_name: redis_app
      command: redis-server --save 20 1 --loglevel warning
      ports:
        - "6379:6379" # Проброс портов: 6379 на хосте к 6379 в контейнере
      volumes:
          - .data.cache:/data
      networks:
        - app-network

  web:
    image: nginx:latest # Docker-образ для веб-сервера (здесь используется Nginx)
    ports:
      - "80:80" # Проброс портов: 80 на хосте к 80 в контейнере
    volumes:
      - ./web:/usr/share/nginx/html # Монтируем локальную папку в контейнер

    networks:
      - app-network

  db:
    image: postgres # Docker-образ для PostgreSQL
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      PGDATA: /var/lib/postgresql/data/pgdata

    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata # Монтируем volume для сохранения данных

    ports:
      - "5432:5432"

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - app-network


  app:
    build: .
    tty: true
    command:
      - /bin/bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000" # Проброс портов: 8000 на хосте к 8000 в контейнере

    depends_on:
      db:
          condition: service_healthy


    env_file:
      - .env

    volumes:
      - .:/code

    networks:
      - app-network


  celery:
    restart: always
    build: .
    tty: true
    container_name: celery
    command: >
            bash -c "celery -A config worker --beat --loglevel=info"
    depends_on:
      - redis
      - app # Зависимость от сервиса приложения

    networks:
      - app-network


  celery_beat:
    build: .
    tty: true
    command: celery -A config beat -l INFO -S django
    depends_on:
      - redis
      - app # Зависимость от сервиса приложения

    networks:
      - app-network

volumes:
  postgres-data:
networks:
  app-network:
    driver: bridge`